### ISSUE TITLE
Port not updating after update.

### ISSUE THREAD

**Issue by patsandy100** [maah/ProtonVPN-win-app#1]
Hello,

Everything was working as expected on the older version I did the update today but am unable to get the port to update automatically. I have tried re-setting webgui password and restarting proton/qbittorent. Not sure if I am doing something wrong or overlooking something.
Cheers!

**Comment by maah** [comment]
I'm not able to reproduce this.

It works fine both on my PC, and on VM with a fresh install (even after installing the older version first).
The update didn't change how the port gets updated either, so it sounds like a misconfiguration on your part (wrong user/password/webgui port?).

Screenshots might help, but it's possible that you changed qbittorrent's settings before and only noticed now?

**Comment by patsandy100** [comment]
Looks like a system reboot did the trick. I even uninstalled and reinstalled the proton package and updated Qbittorent earlier. Apologies to waste your time. IT 101, restart it. 🤦 

Cheers mate. Love your work.

**Comment by maah** [comment]
A reboot should not be required but I'll keep this in mind, thanks! :)
